export const FETCH_PLAYERS = 'GET_PLAYERS';
export const FETCH_PLAYER = 'GET_PLAYER';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';

export const PLAYER_FETCHED = 'PLAYER_FETCHED';
export const PLAYERS_FETCHED = 'PLAYERS_FETCHED';
export const PLAYER_CREATED = 'PLAYER_CREATED';
export const PLAYER_UPDATED = 'PLAYER_UPDATED';
export const PLAYER_DELETED = 'PLAYER_DELETED';
