export const FETCH_USERS = 'GET_USERS'
export const FETCH_USER = 'GET_USER'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'

export const USER_FETCHED = 'USER_FETCHED'
export const USERS_FETCHED = 'USERS_FETCHED'
export const USER_CREATED = 'USER_CREATED'
export const USER_UPDATED = 'USER_UPDATED'
export const USER_DELETED = 'USER_DELETED'
